### ISSUE TITLE
Message filter for Box.Name ("_Box.Name") is not supported

### ISSUE THREAD

**Issue by dixonsiu** [personium/personium-core#59] opened 2017-10-16 07:06 UTC
The following filter query for box messages is not supported currently.  

   https://<Cell URL>/ __ctl/ReceivedMessage?$filter=_Box.Name eq 'io_personium_demo_app-myboard'

For some apps, it is necessary to display certain messages from a specified box.

**Comment by SawamiWataru** [comment] 2019-06-06 05:39
This issue is a duplicate of #55.

**Closed by SawamiWataru** 2019-06-06 05:39 UTC
Labels: duplicate, enhancement
